### ISSUE TITLE
Not able to set 'object-id' and 'element-id' manually of any resource object in zhmcclient_mock

### ISSUE THREAD

**Issue by pranjank** [zhmcclient/python-zhmcclient#239] opened 2017-04-12 12:26 UTC
As of now 'object-id' and 'element-id' are automatically generating by zhmcclient_mock. Which is basically integer value. But to test some function we need 'object-id' in this format [a-f0-9]{8}-([a-f0-9]{4}-){3}[a-f0-9]{12}:[0-3]. 

Even I tried setting up these parameter manually but it is not taking my value. It is overridden by automatically generated (integer) value.

So
1. Either generate 'object-id' in [a-f0-9]{8}-([a-f0-9]{4}-){3}[a-f0-9]{12}:[0-3] format instead of integer value
2. Or allow me to set up  'object-id' parameter for any resource object.

**Comment by andy-maier** [comment] 2017-04-12 17:32
PR #240 improves the testcases, and shows that so far the IDs can successfully be set during object initialization and are not overridden.

We need more precise input to see what the problem is.

**Comment by pranjank** [comment] 2017-04-12 23:50
@andy-maier I am really sorry for that. I was wrongly setting for other resource and checking for another resource.

**Comment by andy-maier** [comment] 2017-04-13 05:53
@pranjank No problem at all, Prabhat. The test cases are now better than before :-)
Closing this issue.

**Closed** 2017-04-13 05:54 UTC
Labels: priority, resolution: no issue
